global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - localhost:9093

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'substans-backend'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: /metrics

  - job_name: 'substans-agents'
    static_configs:
      - targets: ['localhost:8001']
    metrics_path: /agents/metrics

  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:9121']

  - job_name: 'postgres'
    static_configs:
      - targets: ['localhost:9187']